# https://dev.to/willvelida/pushing-container-images-to-github-container-registry-with-github-actions-1m6b
name: Builds the CI/Dev Image

on:
  push:
    branches:
      - main

jobs:
      push-store-image:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build & Push CI Image'
            run: |
              docker build . --tag ghcr.io/edgeless-project/ci-image:latest
              docker push ghcr.io/edgeless-project/ci-image:latest